name: Node.js CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      commit:
        log: 'Commit Log Message'  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install notablog
      run: npm i -g notablog
    - name: Generate static files from notion url
      run: notablog generate .
    - name: Move public files to root folder
      run: |
       cp -r public/* .
       rm -rf public
    - name: Check changed then commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master
        if [[ `git status --porcelain` ]]; then
          git add .
          # Default commit log message
          COMMIT_LOG="Add changes"
          echo "Commit Log Message: ${{ github.event.inputs.commit.log }}"
          if [[ -z "${{ github.event.inputs.commit.log }}" ]]; then
            COMMIT_LOG=${{ github.event.inputs.commit.log }}
          fi
          git commit -m "$COMMIT_LOG" -a
        else
          echo "Nothing changed here"
        fi
 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
